descKeys = {
    "MEIJER EXPRESS": "Gas",
    "SUNRISE": "Gas",
    "SPEEDWAY": "Gas",
    "LOWELL MART": "Gas",
    "BP": "Gas",
    "CIRCLE K": "Gas",
    "SHELL": "Gas",
    "MARATHON": "Gas",
    "EXXON": "Gas",
    "SUNOCO": "Gas",
    "PHILLIPS 66": "Gas",
    "CHEVRON": "Gas",
    "TEXACO": "Gas",
    "AMPM": "Gas",
    
    "AMAZON": "Shopping",
    "MEIJER": "Shopping",
    "TARGET": "Shopping",
    "WAL-MART": "Shopping",
    "DOLLARTREE": "Shopping",
    "NEXT DOOR": "Shopping",
    "AMZN": "Shopping",
    "KROGER": "Shopping",
    "BEST BUY": "Shopping",
    "TJ MAXX": "Shopping",
    "MARSHALLS": "Shopping",
    "BURLINGTON": "Shopping",
    "KOHL'S": "Shopping",
    "ROSS": "Shopping",
    "NORDSTROM": "Shopping",
    "MACY'S": "Shopping",
    "BATH & BODY WORKS": "Shopping",
    "VICTORIA'S SECRET": "Shopping",
    "H&M": "Shopping",
    "ZARA": "Shopping",
    "GAMESTOP": "Shopping",
    "HOME DEPOT": "Shopping",
    "LOWE'S": "Shopping",
    "MENARDS": "Shopping",
    "STAPLES": "Shopping",
    "OFFICE DEPOT": "Shopping",
    
    "TRADER JOE": "Groceries",
    "ALDI": "Groceries",
    "COSTCO": "Groceries",
    "GROCERY": "Groceries",
    "SAM'S CLUB": "Groceries",
    "WHOLE FOODS": "Groceries",
    "SPROUTS": "Groceries",
    "FRESH THYME": "Groceries",
    "SAFEWAY": "Groceries",
    "PUBLIX": "Groceries",
    "HY-VEE": "Groceries",
    "WEGMANS": "Groceries",
    "WINCO": "Groceries",
    
    "PAYROLL": "Paycheck",
    "DIRECT DEPOSIT": "Paycheck",
    
    "INSURANCE": "Insurance",
    "GEICO": "Insurance",
    "STATE FARM": "Insurance",
    "ALLSTATE": "Insurance",
    "PROGRESSIVE": "Insurance",
    "USAA": "Insurance",
    "NATIONWIDE": "Insurance",
    "HUMANA": "Insurance",
    "BLUE CROSS": "Insurance",
    
    "AMK GVSU": "Fast Food",
    "MCDONALD'S": "Fast Food",
    "CULVERS": "Fast Food",
    "TACO BELL": "Fast Food",
    "CHICK-FIL-A": "Fast Food",
    "QDOBA": "Fast Food",
    "JIMMY JOHNS": "Fast Food",
    "FREDDY": "Fast Food",
    "PITA WAY": "Fast Food",
    "THE PUMP HOUSE": "Fast Food",
    "PIZZA": "Fast Food",
    "WENDY'S": "Fast Food",
    "BURGER KING": "Fast Food",
    "ARBY'S": "Fast Food",
    "SONIC": "Fast Food",
    "WHITE CASTLE": "Fast Food",
    "RAISING CANE'S": "Fast Food",
    "CHECKERS": "Fast Food",
    "HARDEE'S": "Fast Food",
    "POPEYES": "Fast Food",
    "DUNKIN'": "Fast Food",
    
    "PALIO": "Restaurant",
    "SUSHI GOGO": "Restaurant",
    "MAIN STREET PUB": "Restaurant",
    "DAVE AND BUSTERS": "Restaurant",
    "OUTBACK STEAKHOUSE": "Restaurant",
    "TEXAS ROADHOUSE": "Restaurant",
    "OLIVE GARDEN": "Restaurant",
    "RED LOBSTER": "Restaurant",
    "BUFFALO WILD WINGS": "Restaurant",
    "CHILI'S": "Restaurant",
    "APPLEBEE'S": "Restaurant",
    "IHOP": "Restaurant",
    "DENNY'S": "Restaurant",
    "BJ'S BREWHOUSE": "Restaurant",
    
    "FOXTAIL": "Coffee Shops",
    "BIGGBY": "Coffee Shops",
    "LANTERN": "Coffee Shops",
    "STARBUCKS": "Coffee Shops",
    "DUNKIN'": "Coffee Shops",
    "TIM HORTONS": "Coffee Shops",
    "PEET'S COFFEE": "Coffee Shops",
    
    "APPLE": "Electronics & Software",
    "SPOTIFY": "Electronics & Software",
    "ADOBE": "Electronics & Software",
    "MICROSOFT": "Electronics & Software",
    "GOOGLE": "Electronics & Software",
    "NETFLIX": "Electronics & Software",
    "HULU": "Electronics & Software",
    "DISNEY+": "Electronics & Software",
    "AMAZON PRIME": "Electronics & Software",
    
    "WALGREENS": "Pharmacy",
    "CVS": "Pharmacy",
    "RITE AID": "Pharmacy",
    
    "INTEREST PAID": "Interest",
    
    "FUNDS TRANSFER": "Transfer",
    "VENMO": "Transfer",
    "PAYPAL": "Transfer",
    "CASH APP": "Transfer",
    "ZELLE": "Transfer",
    
    "DISCOVER": "Credit Card",
    "VISA": "Credit Card",
    "MASTERCARD": "Credit Card",
    "AMERICAN EXPRESS": "Credit Card",
    
    "GOODWILL": "Thrift",
    "MEL TROTTER MISSION": "Thrift",
    "THE SALVATION ARMY": "Thrift",
    "NEW 2 YOU": "Thrift",
    "VOLUNTEERS OF AMERICA": "Thrift",
    "ESTATE SALES": "Thrift",
    "HABITAT FOR HUMANITY": "Thrift",
    "PLATO'S CLOSET": "Thrift",
    
    "CELEBRATION CINEMA": "Entertainment",
    "AMC": "Entertainment",
    "REGAL": "Entertainment",
    "NETFLIX": "Entertainment",
    "HULU": "Entertainment",
    "DISNEY+": "Entertainment",
    "SPOTIFY": "Entertainment",
    
    "THE BOB": "Bar",
    "NEW HOLLAND BREWING": "Bar",
    "BACK FORTY": "Bar",
    "DOWNTOWN": "Bar",
    "BUFFALO WILD WINGS": "Bar",
    
    "FAST STOP": "Car",
    "FOX SHINE": "Car",
    "JIFFY LUBE": "Car",
    "AUTOZONE": "Car",
    "ADVANCE AUTO PARTS": "Car",
    "O'REILLY AUTO PARTS": "Car",
    
    "PARKING": "Parking",
    "METRO PARKING": "Parking",
    "PARKMOBILE": "Parking",
    
    "PETCO": "Pet",
    "PETSMART": "Pet",
    
    "CONNECT4EDUCATION": "Education",
    "ACADLY": "Education",
    "GRAND VALLEY": "Education",
    "GVSU": "Education",
    "COURSERA": "Education",
    "UDACITY": "Education",
    "UDemy": "Education",
    
    "COINBASE": "Crypto",
    "BINANCE": "Crypto",
    "KRAKEN": "Crypto",
    
    "LIQUOR": "Alcohol",
    "TOTAL WINE": "Alcohol",
    "BEVMO": "Alcohol",
    "ABC LIQUOR": "Alcohol",
}
