descKeys = {
    "MEIJER EXPRESS": "Gas",
    "SUNRISE": "Gas",
    "SPEEDWAY": "Gas",
    "LOWELL MART": "Gas",
    "BP": "Gas",
    "CIRCLE K": "Gas",
    "SHELL": "Gas",
    "MARATHON": "Gas",
    "EXXON": "Gas",
    "SUNOCO": "Gas",
    "PHILLIPS 66": "Gas",
    "CHEVRON": "Gas",
    "TEXACO": "Gas",
    "AMPM": "Gas",
    
    "AMAZON": "Shopping",
    "MEIJER": "Shopping",
    "TARGET": "Shopping",
    "WAL-MART": "Shopping",
    "DOLLARTREE": "Shopping",
    "NEXT DOOR": "Shopping",
    "AMZN": "Shopping",
    "KROGER": "Shopping",
    "BEST BUY": "Shopping",
    "TJ MAXX": "Shopping",
    "MARSHALLS": "Shopping",
    "BURLINGTON": "Shopping",
    "KOHL'S": "Shopping",
    "ROSS": "Shopping",
    "NORDSTROM": "Shopping",
    "MACY'S": "Shopping",
    "BATH & BODY WORKS": "Shopping",
    "VICTORIA'S SECRET": "Shopping",
    "H&M": "Shopping",
    "ZARA": "Shopping",
    "GAMESTOP": "Shopping",
    "HOME DEPOT": "Shopping",
    "LOWE'S": "Shopping",
    "MENARDS": "Shopping",
    "STAPLES": "Shopping",
    "OFFICE DEPOT": "Shopping",
    
    "TRADER JOE": "Groceries",
    "ALDI": "Groceries",
    "COSTCO": "Groceries",
    "GROCERY": "Groceries",
    "SAM'S CLUB": "Groceries",
    "WHOLE FOODS": "Groceries",
    "SPROUTS": "Groceries",
    "FRESH THYME": "Groceries",
    "SAFEWAY": "Groceries",
    "PUBLIX": "Groceries",
    "HY-VEE": "Groceries",
    "WEGMANS": "Groceries",
    "WINCO": "Groceries",
    
    "PAYROLL": "Paycheck",
    "DIRECT DEPOSIT": "Paycheck",
    
    "INSURANCE": "Insurance",
    "GEICO": "Insurance",
    "STATE FARM": "Insurance",
    "ALLSTATE": "Insurance",
    "PROGRESSIVE": "Insurance",
    "USAA": "Paycheck",
    "NATIONWIDE": "Insurance",
    "HUMANA": "Insurance",
    "BLUE CROSS": "Insurance",
    
    "AMK GVSU": "Fast Food",
    "MCDONALD'S": "Fast Food",
    "CULVERS": "Fast Food",
    "TACO BELL": "Fast Food",
    "CHICK-FIL-A": "Fast Food",
    "QDOBA": "Fast Food",
    "JIMMY JOHNS": "Fast Food",
    "FREDDY": "Fast Food",
    "PITA WAY": "Fast Food",
    "THE PUMP HOUSE": "Fast Food",
    "PIZZA": "Fast Food",
    "WENDY'S": "Fast Food",
    "BURGER KING": "Fast Food",
    "ARBY'S": "Fast Food",
    "SONIC": "Fast Food",
    "WHITE CASTLE": "Fast Food",
    "RAISING CANE'S": "Fast Food",
    "CHECKERS": "Fast Food",
    "HARDEE'S": "Fast Food",
    "POPEYES": "Fast Food",
    "DUNKIN'": "Fast Food",
    
    "PALIO": "Restaurant",
    "SUSHI GOGO": "Restaurant",
    "MAIN STREET PUB": "Restaurant",
    "DAVE AND BUSTERS": "Restaurant",
    "OUTBACK STEAKHOUSE": "Restaurant",
    "TEXAS ROADHOUSE": "Restaurant",
    "OLIVE GARDEN": "Restaurant",
    "RED LOBSTER": "Restaurant",
    "BUFFALO WILD WINGS": "Restaurant",
    "CHILI'S": "Restaurant",
    "APPLEBEE'S": "Restaurant",
    "IHOP": "Restaurant",
    "DENNY'S": "Restaurant",
    "BJ'S BREWHOUSE": "Restaurant",
    
    "FOXTAIL": "Coffee Shops",
    "BIGGBY": "Coffee Shops",
    "LANTERN": "Coffee Shops",
    "STARBUCKS": "Coffee Shops",
    "DUNKIN'": "Coffee Shops",
    "TIM HORTONS": "Coffee Shops",
    "PEET'S COFFEE": "Coffee Shops",
    
    "APPLE": "Electronics & Software",
    "SPOTIFY": "Electronics & Software",
    "ADOBE": "Electronics & Software",
    "MICROSOFT": "Electronics & Software",
    "GOOGLE": "Electronics & Software",
    "NETFLIX": "Electronics & Software",
    "HULU": "Electronics & Software",
    "DISNEY+": "Electronics & Software",
    "AMAZON PRIME": "Electronics & Software",
    
    "WALGREENS": "Pharmacy",
    "CVS": "Pharmacy",
    "RITE AID": "Pharmacy",
    
    "INTEREST PAID": "Interest",
    
    "FUNDS TRANSFER": "Transfer",
    "VENMO": "Transfer",
    "PAYPAL": "Transfer",
    "CASH APP": "Transfer",
    "ZELLE": "Transfer",
    
    "DISCOVER": "Credit Card",
    "VISA": "Credit Card",
    "MASTERCARD": "Credit Card",
    "AMERICAN EXPRESS": "Credit Card",
    
    "GOODWILL": "Thrift",
    "MEL TROTTER MISSION": "Thrift",
    "THE SALVATION ARMY": "Thrift",
    "NEW 2 YOU": "Thrift",
    "VOLUNTEERS OF AMERICA": "Thrift",
    "ESTATE SALES": "Thrift",
    "HABITAT FOR HUMANITY": "Thrift",
    "PLATO'S CLOSET": "Thrift",
    
    "CELEBRATION CINEMA": "Entertainment",
    "AMC": "Entertainment",
    "REGAL": "Entertainment",
    "NETFLIX": "Entertainment",
    "HULU": "Entertainment",
    "DISNEY+": "Entertainment",
    "SPOTIFY": "Entertainment",
    
    "THE BOB": "Bar",
    "NEW HOLLAND BREWING": "Bar",
    "BACK FORTY": "Bar",
    "DOWNTOWN": "Bar",
    "BUFFALO WILD WINGS": "Bar",
    
    "FAST STOP": "Car",
    "FOX SHINE": "Car",
    "JIFFY LUBE": "Car",
    "AUTOZONE": "Car",
    "ADVANCE AUTO PARTS": "Car",
    "O'REILLY AUTO PARTS": "Car",
    "SUBARU": "Car",
    
    "PARKING": "Parking",
    "METRO PARKING": "Parking",
    "PARKMOBILE": "Parking",
    
    "PETCO": "Pet",
    "PETSMART": "Pet",
    
    "CONNECT4EDUCATION": "Education",
    "ACADLY": "Education",
    "GRAND VALLEY": "Education",
    "GVSU": "Education",
    "COURSERA": "Education",
    "UDACITY": "Education",
    "UDemy": "Education",
    
    "COINBASE": "Crypto",
    "BINANCE": "Crypto",
    "KRAKEN": "Crypto",
    
    "LIQUOR": "Alcohol",
    "TOTAL WINE": "Alcohol",
    "BEVMO": "Alcohol",
    "ABC LIQUOR": "Alcohol",
    "GRAND VALLEY STA": "Payment",
    "HAMPTON": "Hotel",
    "JJ GHOTRA": "Restaurant",
    "PBC WALKER": "Gas Station",
    "HOWARD CITY MOBIL MART": "Gas Station",
    "SNACKS AND SWEETS": "Food",
    "GRAND RAPIDS DOWNTOWN": "Entertainment",
    "GREAT LAKES LAVENDER": "Retail",
    "ARAMARK VENDING": "Vending Machine",
    "BEAD HAVEN": "Retail",
    "FRANKENMUTH LOCATION": "Retail",
    "MODERN LEASING": "Service",
    "HARRYS ONE STOP": "Gas Station",
    "DAVE & BUSTERS": "Entertainment",
    "JERSEY MIKES": "Restaurant",
    "UBER": "Transport",
    "SOCIAL HOUSE": "Restaurant",
    "GR PUBLIC MUSEUM": "Entertainment",
    "MOJOS DUELING PIANO": "Entertainment",
    "FOUNDERS BREWING CO": "Brewery",
    "SEC OF STATE BRANCH": "Government Service",
    "ELAVON SERVICE FEE": "Service Fee",
    "FIVE BELOW": "Retail",
    "MIDNIGHT EXPRESS CAFE": "Restaurant",
    "SCOOPERS ICE CREAM": "Dessert",
    "BLUEHOST.COM": "Web Hosting",
    "HOBBY LOBBY": "Retail",
    "O'BRIENS SCHOOL HOUSE": "Food",
    "FORTNITE": "Gaming",
    "MAGE.SPACE": "Online Service",
    "VITALES ADA": "Restaurant",
    "NONNA'S PANTRY": "Restaurant",
    "OIL CHANGERS": "Car Maintenance",
    "BARNES AND NOBLE": "Bookstore",
    "FAMILY FARE": "Grocery",
    "ADA MARKET": "Grocery",
    "SUBWAY": "Restaurant",
    "GRCC FOOD SERVICE": "Food",
    "PARCHMENT-UNIV DOCS": "Education",
    "STEAMGAMES.COM": "Gaming",
    "AI JOI": "Retail",
    "NORMS ICE CREAM": "Dessert",
    "LYON STREET CAFE": "Cafe",
    "SEPHORA": "Retail",
    "THE BOROUGH": "Restaurant",
    "HUGGY BEAR CAMPGROUND": "Lodging",
    "AMF BOWLING": "Entertainment",
    "NAYAX VENDING": "Vending Machine",
    "HAPPY CAT CAFE": "Cafe",
    "LITTLE CAESARS": "Restaurant",
    "MCGRAW-HILL HIGHER ED": "Education",
    "DAVE & BUSTER'S MOBILE": "Entertainment",
    "LOVE'S": "Gas Station",
    "DUNKIN": "Cafe"
}
